-- MySQL Script generated by MySQL Workbench
-- Wed Aug  2 20:55:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DumBass
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DumBass` ;

-- -----------------------------------------------------
-- Schema DumBass
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DumBass` DEFAULT CHARACTER SET utf8 ;
USE `DumBass` ;

-- -----------------------------------------------------
-- Table `DumBass`.`Settore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DumBass`.`Settore` (
  `idSettore` INT NOT NULL AUTO_INCREMENT,
  `nomeSettore` VARCHAR(100) NOT NULL,
  `settorePadre` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idSettore`),
  INDEX `fk.idSettore_idx` (`settorePadre` ASC) VISIBLE,
  UNIQUE INDEX `settorePadre_UNIQUE` (`settorePadre` ASC) VISIBLE,
  CONSTRAINT `fk.settore.idSettore`
    FOREIGN KEY (`settorePadre`)
    REFERENCES `DumBass`.`Settore` (`idSettore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DumBass`.`Impostazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DumBass`.`Impostazione` (
  `idImpostazione` INT NOT NULL AUTO_INCREMENT,
  `tema` VARCHAR(50) NOT NULL,
  `filtroDaltonici` VARCHAR(45) NULL,
  PRIMARY KEY (`idImpostazione`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DumBass`.`Utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DumBass`.`Utente` (
  `idUtente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NULL,
  `cognome` VARCHAR(128) NULL,
  `email` VARCHAR(128) NULL,
  `username` VARCHAR(128) NULL,
  `dataNascita` DATE NULL,
  `telefono` VARCHAR(45) NULL,
  `idSettore` INT NULL,
  `idImpostazione` INT NULL,
  PRIMARY KEY (`idUtente`),
  INDEX `fk.idSettore_idx` (`idSettore` ASC) VISIBLE,
  UNIQUE INDEX `idSettore_UNIQUE` (`idSettore` ASC) VISIBLE,
  INDEX `fk.idImpostazione_idx` (`idImpostazione` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk.utente.idSettore`
    FOREIGN KEY (`idSettore`)
    REFERENCES `DumBass`.`Settore` (`idSettore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk.utente.idImpostazione`
    FOREIGN KEY (`idImpostazione`)
    REFERENCES `DumBass`.`Impostazione` (`idImpostazione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DumBass`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DumBass`.`Post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `testo` VARCHAR(45) NULL,
  `idSettore` INT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`idPost`),
  INDEX `fk.idSettore_idx` (`idSettore` ASC) VISIBLE,
  UNIQUE INDEX `idSettore_UNIQUE` (`idSettore` ASC) VISIBLE,
  CONSTRAINT `fk.post.idSettore`
    FOREIGN KEY (`idSettore`)
    REFERENCES `DumBass`.`Settore` (`idSettore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DumBass`.`Allegato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DumBass`.`Allegato` (
  `idAllegato` INT NOT NULL AUTO_INCREMENT,
  `data` BLOB NULL,
  `tipo` VARCHAR(45) NULL,
  `idPost` INT NULL,
  PRIMARY KEY (`idAllegato`),
  INDEX `fk.idPost_idx` (`idPost` ASC) VISIBLE,
  CONSTRAINT `fk.allegato.idPost`
    FOREIGN KEY (`idPost`)
    REFERENCES `DumBass`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DumBass`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DumBass`.`Tag` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idTag`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DumBass`.`Etichettamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DumBass`.`Etichettamento` (
  `idEtichettamento` INT NOT NULL AUTO_INCREMENT,
  `idPost` INT NOT NULL,
  `idTag` INT NOT NULL,
  PRIMARY KEY (`idEtichettamento`),
  UNIQUE INDEX `idPost_UNIQUE` (`idPost` ASC) VISIBLE,
  UNIQUE INDEX `idTag_UNIQUE` (`idTag` ASC) VISIBLE,
  CONSTRAINT `fk.etichett.idPost`
    FOREIGN KEY (`idPost`)
    REFERENCES `DumBass`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk.etichett.idTag`
    FOREIGN KEY (`idTag`)
    REFERENCES `DumBass`.`Tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DumBass`.`Notifica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DumBass`.`Notifica` (
  `idNotifica` INT NOT NULL AUTO_INCREMENT,
  `letta` TINYINT NULL,
  `tipo` INT NULL,
  `idUtente` INT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`idNotifica`),
  INDEX `fk.idUtente_idx` (`idUtente` ASC) VISIBLE,
  CONSTRAINT `fk.notifica.idUtente`
    FOREIGN KEY (`idUtente`)
    REFERENCES `DumBass`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DumBass`.`Pubblicazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DumBass`.`Pubblicazione` (
  `idPubblicazione` INT NOT NULL AUTO_INCREMENT,
  `idUtente` INT NULL,
  `collaboratore` TINYINT NULL DEFAULT 0,
  `idPost` INT NULL,
  PRIMARY KEY (`idPubblicazione`),
  UNIQUE INDEX `idAutore_UNIQUE` (`idUtente` ASC) VISIBLE,
  INDEX `fk.idPost_idx` (`idPost` ASC) VISIBLE,
  CONSTRAINT `fk.pubblicazione.idUtente`
    FOREIGN KEY (`idUtente`)
    REFERENCES `DumBass`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk.pubblicazione.idPost`
    FOREIGN KEY (`idPost`)
    REFERENCES `DumBass`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DumBass`.`Salvataggio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DumBass`.`Salvataggio` (
  `idSalvataggio` INT NOT NULL AUTO_INCREMENT,
  `idUtente` INT NULL,
  `idPost` INT NULL,
  PRIMARY KEY (`idSalvataggio`),
  UNIQUE INDEX `idUtente_UNIQUE` (`idUtente` ASC) VISIBLE,
  UNIQUE INDEX `idPost_UNIQUE` (`idPost` ASC) VISIBLE,
  CONSTRAINT `fk.salvataggio.idUtente`
    FOREIGN KEY (`idUtente`)
    REFERENCES `DumBass`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk.salvataggio.idPost`
    FOREIGN KEY (`idPost`)
    REFERENCES `DumBass`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DumBass`.`Amicizia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DumBass`.`Amicizia` (
  `idAmicizia` INT NOT NULL AUTO_INCREMENT,
  `idSeguace` INT NULL,
  `idSeguito` INT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`idAmicizia`),
  UNIQUE INDEX `idSeguace_UNIQUE` (`idSeguace` ASC, `idSeguito` ASC) VISIBLE,
  CONSTRAINT `fk.amicizia.idSeguace`
    FOREIGN KEY (`idSeguace`)
    REFERENCES `DumBass`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk.amicizia.idSeguito`
    FOREIGN KEY (`idSeguito`)
    REFERENCES `DumBass`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DumBass`.`Credenziali`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DumBass`.`Credenziali` (
  `idCredenziali` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NULL,
  `idUtente` INT NOT NULL,
  PRIMARY KEY (`idCredenziali`),
  UNIQUE INDEX `idUtente_UNIQUE` (`idUtente` ASC) VISIBLE,
  CONSTRAINT `fk.credenziali.idUtente`
    FOREIGN KEY (`idUtente`)
    REFERENCES `DumBass`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DumBass`.`Commento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DumBass`.`Commento` (
  `idCommento` INT NOT NULL,
  `testo` VARCHAR(256) NULL,
  `idUtente` INT NOT NULL,
  `idPost` INT NOT NULL,
  PRIMARY KEY (`idCommento`),
  INDEX `idUtente_idx` (`idUtente` ASC) VISIBLE,
  INDEX `idPost_idx` (`idPost` ASC) VISIBLE,
  CONSTRAINT `idUtente`
    FOREIGN KEY (`idUtente`)
    REFERENCES `DumBass`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPost`
    FOREIGN KEY (`idPost`)
    REFERENCES `DumBass`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `DumBass`;

DELIMITER $$
USE `DumBass`$$
CREATE DEFINER = CURRENT_USER TRIGGER `DumBass`.`Tag_AFTER_DELETE` AFTER DELETE ON `Tag` FOR EACH ROW
BEGIN

END
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
