-- MySQL Script generated by MySQL Workbench
-- Sat Aug 19 11:57:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema epiz_34305586_solveit
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS `epiz_34305586_solveit` ;

-- -----------------------------------------------------
-- Schema epiz_34305586_solveit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `epiz_34305586_solveit` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `epiz_34305586_solveit` ;

-- -----------------------------------------------------
-- Table `epiz_34305586_solveit`.`Settore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epiz_34305586_solveit`.`Settore` (
  `idSettore` INT NOT NULL AUTO_INCREMENT,
  `nomeSettore` VARCHAR(100) NOT NULL,
  `settorePadre` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idSettore`),
  INDEX `fk.idSettore_idx` (`settorePadre` ASC) ,
  UNIQUE INDEX `settorePadre_UNIQUE` (`settorePadre` ASC) ,
  CONSTRAINT `fk.settore.idSettore`
    FOREIGN KEY (`settorePadre`)
    REFERENCES `epiz_34305586_solveit`.`Settore` (`idSettore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epiz_34305586_solveit`.`Impostazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epiz_34305586_solveit`.`Impostazione` (
  `idImpostazione` INT NOT NULL AUTO_INCREMENT,
  `tema` VARCHAR(50) NOT NULL,
  `filtroDaltonici` VARCHAR(45) NULL,
  PRIMARY KEY (`idImpostazione`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epiz_34305586_solveit`.`Utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epiz_34305586_solveit`.`Utente` (
  `idUtente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NULL,
  `cognome` VARCHAR(128) NULL,
  `email` VARCHAR(128) NULL,
  `username` VARCHAR(128) NULL,
  `dataNascita` DATE NULL,
  `telefono` VARCHAR(45) NULL,
  `idSettore` INT NULL,
  `idImpostazione` INT NULL,
  PRIMARY KEY (`idUtente`),
  INDEX `fk.idSettore_idx` (`idSettore` ASC) ,
  UNIQUE INDEX `idSettore_UNIQUE` (`idSettore` ASC) ,
  INDEX `fk.idImpostazione_idx` (`idImpostazione` ASC) ,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  CONSTRAINT `fk.utente.idSettore`
    FOREIGN KEY (`idSettore`)
    REFERENCES `epiz_34305586_solveit`.`Settore` (`idSettore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk.utente.idImpostazione`
    FOREIGN KEY (`idImpostazione`)
    REFERENCES `epiz_34305586_solveit`.`Impostazione` (`idImpostazione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epiz_34305586_solveit`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epiz_34305586_solveit`.`Post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `testo` VARCHAR(256) NULL,
  `idSettore` INT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `titolo` VARCHAR(128) NULL,
  PRIMARY KEY (`idPost`),
  INDEX `fk.idSettore_idx` (`idSettore` ASC) ,
  CONSTRAINT `fk.post.idSettore`
    FOREIGN KEY (`idSettore`)
    REFERENCES `epiz_34305586_solveit`.`Settore` (`idSettore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epiz_34305586_solveit`.`Allegato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epiz_34305586_solveit`.`Allegato` (
  `idAllegato` INT NOT NULL AUTO_INCREMENT,
  `data` LONGBLOB NULL,
  `tipo` VARCHAR(256) NULL,
  `idPost` INT NULL,
  `nome` VARCHAR(256) NULL,
  PRIMARY KEY (`idAllegato`),
  INDEX `fk.idPost_idx` (`idPost` ASC) ,
  CONSTRAINT `fk.allegato.idPost`
    FOREIGN KEY (`idPost`)
    REFERENCES `epiz_34305586_solveit`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epiz_34305586_solveit`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epiz_34305586_solveit`.`Tag` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idTag`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epiz_34305586_solveit`.`Etichettamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epiz_34305586_solveit`.`Etichettamento` (
  `idEtichettamento` INT NOT NULL AUTO_INCREMENT,
  `idPost` INT NOT NULL,
  `idTag` INT NOT NULL,
  PRIMARY KEY (`idEtichettamento`),
  UNIQUE INDEX `idPost_UNIQUE` (`idPost` ASC) ,
  UNIQUE INDEX `idTag_UNIQUE` (`idTag` ASC) ,
  CONSTRAINT `fk.etichett.idPost`
    FOREIGN KEY (`idPost`)
    REFERENCES `epiz_34305586_solveit`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk.etichett.idTag`
    FOREIGN KEY (`idTag`)
    REFERENCES `epiz_34305586_solveit`.`Tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epiz_34305586_solveit`.`Notifica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epiz_34305586_solveit`.`Notifica` (
  `idNotifica` INT NOT NULL AUTO_INCREMENT,
  `letta` TINYINT NULL,
  `tipo` INT NULL,
  `idUtente` INT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`idNotifica`),
  INDEX `fk.idUtente_idx` (`idUtente` ASC) ,
  CONSTRAINT `fk.notifica.idUtente`
    FOREIGN KEY (`idUtente`)
    REFERENCES `epiz_34305586_solveit`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epiz_34305586_solveit`.`Pubblicazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epiz_34305586_solveit`.`Pubblicazione` (
  `idPubblicazione` INT NOT NULL AUTO_INCREMENT,
  `idUtente` INT NULL,
  `collaboratore` TINYINT NULL DEFAULT 0,
  `idPost` INT NULL,
  PRIMARY KEY (`idPubblicazione`),
  INDEX `fk.idPost_idx` (`idPost` ASC) ,
  INDEX `autorePost` (`idPost` ASC, `idUtente` ASC) ,
  CONSTRAINT `fk.pubblicazione.idUtente`
    FOREIGN KEY (`idUtente`)
    REFERENCES `epiz_34305586_solveit`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk.pubblicazione.idPost`
    FOREIGN KEY (`idPost`)
    REFERENCES `epiz_34305586_solveit`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epiz_34305586_solveit`.`Salvataggio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epiz_34305586_solveit`.`Salvataggio` (
  `idSalvataggio` INT NOT NULL AUTO_INCREMENT,
  `idUtente` INT NOT NULL,
  `idPost` INT NOT NULL,
  PRIMARY KEY (`idSalvataggio`),
  INDEX `idx.salvataggio.utentePost` (`idUtente` ASC, `idPost` ASC) ,
  CONSTRAINT `fk.salvataggio.idUtente`
    FOREIGN KEY (`idUtente`)
    REFERENCES `epiz_34305586_solveit`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk.salvataggio.idPost`
    FOREIGN KEY (`idPost`)
    REFERENCES `epiz_34305586_solveit`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epiz_34305586_solveit`.`Amicizia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epiz_34305586_solveit`.`Amicizia` (
  `idAmicizia` INT NOT NULL AUTO_INCREMENT,
  `idSeguace` INT NULL,
  `idSeguito` INT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`idAmicizia`),
  UNIQUE INDEX `idSeguace_UNIQUE` (`idSeguace` ASC, `idSeguito` ASC) ,
  CONSTRAINT `fk.amicizia.idSeguace`
    FOREIGN KEY (`idSeguace`)
    REFERENCES `epiz_34305586_solveit`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk.amicizia.idSeguito`
    FOREIGN KEY (`idSeguito`)
    REFERENCES `epiz_34305586_solveit`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epiz_34305586_solveit`.`Credenziali`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epiz_34305586_solveit`.`Credenziali` (
  `idCredenziali` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NULL,
  `idUtente` INT NOT NULL,
  PRIMARY KEY (`idCredenziali`),
  CONSTRAINT `fk.credenziali.idUtente`
    FOREIGN KEY (`idUtente`)
    REFERENCES `epiz_34305586_solveit`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epiz_34305586_solveit`.`Commento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epiz_34305586_solveit`.`Commento` (
  `idCommento` INT NOT NULL AUTO_INCREMENT,
  `testo` VARCHAR(255) NULL,
  `idUtente` INT NOT NULL,
  `idPost` INT NOT NULL,
  `idCommentoPadre` INT NULL,
  `timestamp` DATETIME NULL,
  PRIMARY KEY (`idCommento`),
  INDEX `idUtente_idx` (`idUtente` ASC) ,
  INDEX `idPost_idx` (`idPost` ASC) ,
  INDEX `idCommentoPadre_idx` (`idCommentoPadre` ASC) ,
  CONSTRAINT `fk.commento.idUtente`
    FOREIGN KEY (`idUtente`)
    REFERENCES `epiz_34305586_solveit`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk.commento.idPost`
    FOREIGN KEY (`idPost`)
    REFERENCES `epiz_34305586_solveit`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk.commento.idCommentoPadre`
    FOREIGN KEY (`idCommentoPadre`)
    REFERENCES `epiz_34305586_solveit`.`Commento` (`idCommento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epiz_34305586_solveit`.`MiPiace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epiz_34305586_solveit`.`MiPiace` (
  `idMiPiace` INT NOT NULL AUTO_INCREMENT,
  `idUtente` INT NOT NULL,
  `idPost` INT NOT NULL,
  PRIMARY KEY (`idMiPiace`),
  INDEX `fk.mipiace.idUtente_idx` (`idUtente` ASC) ,
  INDEX `fk.mipiace.idPost_idx` (`idPost` ASC) ,
  UNIQUE INDEX `idx.mipiace.utentePost` (`idUtente` ASC, `idPost` ASC) ,
  CONSTRAINT `fk.mipiace.idUtente`
    FOREIGN KEY (`idUtente`)
    REFERENCES `epiz_34305586_solveit`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk.mipiace.idPost`
    FOREIGN KEY (`idPost`)
    REFERENCES `epiz_34305586_solveit`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
